In [1]:
my_list = [1, 2, 3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

my_math = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
my_math

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
my_math = np.array(my_math)

In [8]:
my_math

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
np.linspace(1,5,15)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ])

In [18]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [19]:
np.random.rand(5)

array([ 0.69621717,  0.19061562,  0.25534642,  0.32663946,  0.86359417])

In [20]:
np.random.randn(2)

array([ 1.98557931, -1.84653668])

In [22]:
np.random.randint(1,100,10)

array([48, 99, 95, 28, 11, 14,  9, 64,  3,  4])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0, 50, 10)

In [28]:
ranarr

array([ 0,  7, 41, 32,  9, 40, 23,  1, 36, 26])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

41

In [33]:
ranarr.min()

0

In [34]:
ranarr

array([ 0,  7, 41, 32,  9, 40, 23,  1, 36, 26])

In [35]:
ranarr.argmax()

2

In [36]:
ranarr.argmin()

0

In [38]:
arr.dtype

dtype('int64')